version: '2.1'
services:
    odoo:
        image: odoo:13.0
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - odoo-data:/var/lib/odoo:rw,z
            - ./:/mnt/extra-addons:ro,z
    db:
        image: docker.io/library/postgres:10.7
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata:rw,Z
    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - "80:8080"
        environment:
            - BASE_URL=/swagger
            - SWAGGER_JSON=/swagger/swagger.json
        volumes:
            - ./swagger:/swagger
volumes:
    odoo-data:
    db-data:
